services:
  bot:
    ports:
      - "3000:3000"
    image: "raid_bot_creater"
    container_name: "raid_bot_container"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/raid_bot"
    volumes:
      - .:/usr/src/app/raid_bot
    command: npm run start
    restart: always
    env_file:
      - ".env"
