services:
  bot:
    ports:
      - "3000:3000"
    image: "raid_bot_creater"
    container_name: "raid_bot_container"
    stop_signal: SIGINT
    build: .
    restart: unless-stopped
    env_file:
      - ".env"
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http --url=sunny-camel-exact.ngrok-free.app 3000
